[package]
name = "example"
version = "0.1.0"
authors = ["Jerry Yang <hy0kle@gmail.com>"]

[dependencies]
time = "*"
ansi_term = "*"
rustc-serialize = "*"

# 测试 MySQL 相关
[dependencies.mysql]
mysql = "*"
default-features = false
features = ["socket"]
